### ISSUE TITLE
Feature Request: Disable/configure large button size

### ISSUE THREAD

**Issue by srounce** [APEbbers/FreeCAD-Ribbon#102]
The large buttons are too large to be useful for me and require a lot of horizontal scrolling in some workbenches. Personally, I'd just like small buttons with labels to the right everywhere. I understand this may not be optimal for everyone, so having this configurable would be great.

There is also the issue of some adjacent buttons using completely different sizes such as in the following example:
![image](https://github.com/user-attachments/assets/78146dc4-7594-49ce-85c8-0d5124e43fcb)

**Comment by APEbbers** [comment]
Hi,

You can configure the ribbon with the ribbon design menu. There you can set buttons to small, medium and large.
![image](https://github.com/user-attachments/assets/382663b6-4ca7-4815-b8ed-5e15165f81bb)
![image](https://github.com/user-attachments/assets/82f866dc-56ac-47cb-b845-2cc41f34af96)

in the preference menu you can set the size of small and medium buttons. (large icons will follow later). Also you can enable or disable text per button size.

Also some scripts are provided. you can open these and change them to your liking. The script set per pane the first button to large and the rest to small.  This can easily changed to small for every button.
  
See the [https://github.com/APEbbers/FreeCAD-Ribbon/wiki](url) for more information. (you can also click on the "about" button in the application menu.

kind regards,
