### ISSUE TITLE
FR: A  button to reset the preferences

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#109]
A suggestion I would like to propose is a button to reset all the values in preferences to their default ones with a click of a button on the same horizontal space as "Cancel" and "Close", preferably to the left.

![image](https://github.com/user-attachments/assets/92eac8df-0f47-4c60-9cea-0b02d256533b)

**Comment by APEbbers** [comment]
Agreed. I added with this release!
