### ISSUE TITLE
The Ribbon Design dialog does not show the panels of the TechDraw workbench correctly; and it is also unable to configure the ribbon for the TechDraw workbench.   

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#112]
As shown below, the Ribbon shows a different list of panels, while the **Ribbon design** dialog shows a different list of panels for this workbench.
![image](https://github.com/user-attachments/assets/639c806f-1e53-4d28-b6a2-3a8e5f822c5d)

As a result, the **Ribbon design** dialog is unable to display/control these panels of the TechDraw workbench.

**Desired:**
The **Ribbon design** dialog must show the correct  panels, and be able to control the actual ribbon.

**Comment by APEbbers** [comment]
This seems the same cache issue. There is an different wb showing. I'll keep a lookout for it but i'm closing it for now

**Comment by raindropsfromsky** [comment]
Is there any workaround? 
For example, can I refresh cache somewhere to get rid of this issue?
