### ISSUE TITLE
Feature request: Allow the user to set a universal default icon size and select the "icon only" checkbox for all panels of all workbenches.

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#116]
The **Ribbon Design** dialog allows us to change the icon size for each panel of each workbench.
This is a fantastic feature.

However, I prefer the following settings for all workbenches:
1. All icons -> small size
2. No text (labels) for any workbench or panels.

So I had to select each workbench and then changing the icon size to small, and selecting the "Icons only" checkbox.
This was too tedious!

Please consider that a vast majority of FreeCAD users would like these settings as default.
Only novices will prefer to display text, or large icons at some places. 
But within a few days, they would also want to change over to the expert mode (small icons, no text.)

Therefore, the settings dialog should have two universal default settings: 
1. Small icons
2. No text (labels)

This should reset the size of all icons to "small", and turn off all labels in all workbenches and panels.

After that, if the user wants, he can always select a particular workbench and panel, and change the settings for specific icon(s).

This will save a lot of labor for the vast majority of FreeCAD users.

**Comment by APEbbers** [comment]
In the next release the scripts is optimized to help with that. in the release after that this is planned for the design menu

**Comment by raindropsfromsky** [comment]
Could you please share the link to the development version?
I can check it out and give advance feedback.

Thanks in advance!

**Comment by APEbbers** [comment]
of course!

[https://github.com/APEbbers/FreeCAD-Ribbon/tree/Develop](url)

**Comment by raindropsfromsky** [comment]
> [https://github.com/APEbbers/FreeCAD-Ribbon/tree/Develop/](url)
I cannot see any content there. Seems to be malformed URL...
![image](https://github.com/user-attachments/assets/945743e6-642c-4bf8-aea6-e881d63cb7a3)

Or perhaps you can see that URL because you are the author.
Others may not be able to see it.

**Comment by APEbbers** [comment]
Seems an issue with github. when you copy/paste the link, it works

**Comment by raindropsfromsky** [comment]
> https://github.com/APEbbers/FreeCAD-Ribbon/tree/Develop

I copied and pasted the link. It goes to the same "code" page of GitHub, where [v1.3.16](https://github.com/APEbbers/FreeCAD-Ribbon/releases/tag/v1.3.16) is listed as the latest version. (It was released 2 weeks ago.)

But I installed Ribbon WB using the Addon Manager, and that version is the latest (1.3.17.2)!
![image](https://github.com/user-attachments/assets/54bbc35b-0491-40fb-9a05-82289fc63182)

So which is the latest development version, and where is it available?

**Comment by APEbbers** [comment]
if you enable the option to switch branches. You can switch to the develop branch (you might have to press update again):
![image](https://github.com/user-attachments/assets/99ab1560-e824-4e42-88a8-2db02f7f85b6)
![image](https://github.com/user-attachments/assets/2ed85c53-e22a-4cfc-9082-7b48554793cc)
![image](https://github.com/user-attachments/assets/da0237f1-e3e2-4d9d-bea2-3c076cd781a9)

or use the link with TorToiseGit if you have it installed.
