### ISSUE TITLE
The Ribbon design dialog does not reflect all panels of the Surface workbench correctly

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#118]
The **Ribbon design** dialog does not reflect all panels of the Surface workbench correctly, as shown in the screenshot below:
![image](https://github.com/user-attachments/assets/d91699a3-94fa-45b6-ba43-57c512ffe873)

The actual workbench has many panels (marked "1").
In fact, some of the panels spill over on the right side of the screen (marked "2").

But the **Ribbon design** dialog shows only three panels (marked "3").

As a result, we cannot customize the ribbon for this workbench.

**Desired:** The **Ribbon design** dialog should shows all panels correctly.

**Comment by APEbbers** [comment]
This seems an cache issue. It is as if the wb is not properly activated.
Sometimes it helps to set the wb to loaded at startup. I have seen this before and changed the code. So I'm closing it for now and mark it as fixed in develop branch.

**Comment by raindropsfromsky** [comment]
> This seems an cache issue. It is as if the wb is not properly activated. Sometimes it helps to set the wb to loaded at startup. I have seen this before and changed the code. So I'm closing it for now and mark it as fixed in develop branch.

I wonder if the other bug I reported also is because of that same reason (when I create a sketch from PD WB, FC switches to Part WB rather than to the Sketcher WB.)

**Comment by raindropsfromsky** [comment]
Just to clear myself about this point, the current version does not appear in the **Preferences** dialog (in the **Available Workbenches** list) at all
![image](https://github.com/user-attachments/assets/df31593b-632b-4e06-b62c-3ca9948ea60c)

Have you changed this behavior?

**Comment by APEbbers** [comment]
Yes, that is because the Ribbon must be loaded at startup to be displayed properly. So it is not a normal add-on like the others.
