### ISSUE TITLE
Feature request: Allow the user to expand the width of the "Ribbon design" dialog

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#119]
In some cases, the content in the panel cannot be read fully.
So the user needs to expand the width of the dialog to read the description fully.

![image](https://github.com/user-attachments/assets/34235a89-8224-4ac4-88a8-83c16a5ca3e5)

However, there's a problem: This dialog cannot be widened.

**Desired:** Please allow the user to expand the width of the "Ribbon design" dialog

**Comment by raindropsfromsky** [comment]
Additionally, it would be great if FreeCAD remembers the width set in the last session, and uses that setting persistently even after the app and/or the laptop is restarted.

**Comment by APEbbers** [comment]
Hi,

I solved this partially. You can now stretch the dialog. But it is not remembered at the moment.

kind regards

**Comment by raindropsfromsky** [comment]
Hopefully that will coom soon! :)
