### ISSUE TITLE
In the "Ribbon settings" dialog, the "General" button is redundant 

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#120]
In the "Ribbon settings" dialog, the "General" button is redundant: It serves no purpose, and it is not even clickable.
![image](https://github.com/user-attachments/assets/a0ac56fc-e897-4c34-acd8-27000212f518)

**Comment by APEbbers** [comment]
hi,

in the next release there will be more tabs
