### ISSUE TITLE
When I create a sketch from the Part Design WB, FC does not switch to Sketcher WB. Sometimes it switches to Part WB.

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#123]
Before installing the Ribbon WB, whenever I created a sketch in the Part Design WB, FC always switched to Sketcher WB automatically.
But after installing the Ribbon WB, FC does not always switch to the Sketcher WB: Sometimes it switches to the Part WB, which is located just after the PD WB in the WB toolbar.

I have to manually select the Sketcher WB.

However, this happens only for one time; and only when I have launched the FC.
Here, when I create a sketch, FC switches to the Part WB, which is located next to the PD WB in the toolbar, as shown below:
![image](https://github.com/user-attachments/assets/ddbb9182-5f8b-4dcd-a81f-a4cbc1c5a8a8)

But now if I discard the file, switch to PD WB, and then create a new file, FC switches to Sketcher without any problem.

My settings are as follows:
![image](https://github.com/user-attachments/assets/13a474aa-5333-498c-8c4c-70e06f90bee1)

OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.39240 (Git) Conda
Build type: Release
Branch: main
Hash: f9ba94c70b139ece6ba5ffba47632d91b5c9c645
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Beltrami 1.1.0
  * btl 0.9.9
  * CurvedShapes 1.0.12
  * Curves 0.6.51
  * ExplodedAssembly
  * fasteners 0.5.29
  * FreeCAD-Ribbon 1.3.17.2
  * OpenTheme 2024.9.1
  * POV-Ray-Rendering
  * QuickMeasure 2022.10.28
  * SearchBar 1.0.2
  * sheetmetal 0.5.3
  * Silk 0.1.5
  * Trails 2022.1.0
  * woodworking 0.21.2.33771

**Comment by APEbbers** [comment]
Seems to be working on my side. I'll close it for now, but I'll keep it in mind.
Probally the same cache issue.
