### ISSUE TITLE
The backup path shows **forward slash** (/) in Windows!

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#124]
The backup path shows **forward slash** (/) in Windows!

![image](https://github.com/user-attachments/assets/22ae74ca-3043-4d75-88ef-e779f5e10163)

**Comment by APEbbers** [comment]
Hi,

That's just notation style. It is still working. 
I'm using the path package in python to have the correct path automatically for each OS. 
On my version, the stylesheet has also a forward slash.

kind regards,
