### ISSUE TITLE
The About FreeCAD Ribbon screen shows redundant buttons that cannot have any use.

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#127]
The **About FreeCAD Ribbon** screen shows redundant buttons that cannot have any use.

![image](https://github.com/user-attachments/assets/d8b92073-2f85-4a2c-abdc-645293dbf066)

**Comment by APEbbers** [comment]
Hi,

This is also fixed with version 1.4.1. a difference between QT5 and QT6 apparently.

kind regards,
