### ISSUE TITLE
Ribbon Design dialog crashes when I try to switch tab to "exclude panels", "Include panels", etc. 

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#128]
Ribbon Design dialog crashes when I try to switch tab to "exclude panels", "Include panels", etc. 
![image](https://github.com/user-attachments/assets/b591ecf8-37ef-4c2e-bfc7-8c58b8977824)

FC does not crash.

OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.39240 (Git) Conda
Build type: Release
Branch: main
Hash: f9ba94c70b139ece6ba5ffba47632d91b5c9c645
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Beltrami 1.1.0
  * btl 0.9.9
  * CurvedShapes 1.0.13
  * Curves 0.6.51
  * ExplodedAssembly
  * fasteners 0.5.31
  * FreeCAD-Ribbon 1.4.0
  * OpenTheme 2024.9.1
  * POV-Ray-Rendering
  * QuickMeasure 2022.10.28
  * SearchBar 1.0.2
  * sheetmetal 0.5.6
  * Silk 0.1.5
  * Trails 2022.1.0
  * woodworking 0.21.2.33771

**Comment by APEbbers** [comment]
Hi,

It should be fixed with version 1.4.1. Stretching still works
