### ISSUE TITLE
The labels for panels are too long and complicated in Exploded Assembly WB, which spoils the alignment of toolbar buttons

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#131]
The labels for panels are too long and complicated in Exploded Assembly WB (marked "1").
![image](https://github.com/user-attachments/assets/2e4a064c-b0b1-41d8-a385-9d4d6c792398)

As a result, these panels become too wide, with too few buttons in them.
Consequently, these buttons appear to be scattered (marked "2")

**Suggestions:** 
1. Remove "ExplodedAssembly" at the beginning
3. Remove "tools" at the end

Both these parts are redundant!

Reporting for 1.4.1

**Comment by APEbbers** [comment]
Hi,

For this reason I've created the function "custom toolbars".  You can
create a custom panel based on that toolbar. or combine multiple into one
panel. You can then give it a different name.
I rather not hardcode names for panels for every possible toolbar and
workbench. That will result in a lot of maintenance and people prefer
different names.

kind regards

**Comment by raindropsfromsky** [comment]
Well, a custom toolbar should not be needed as a solution for this issue: It would be enough to clean up the labels for this toolbar as suggested, IMHO.

**Comment by APEbbers** [comment]
I understand. But is not an issue for the Ribbon, but for the workbenches them self. 
The reason that I hesitate to create custom labels is:
 - if I make custom labels, I have to do that for every possible workbench which is a lot of maintenance
 - People preferer different names. So it is never right for everyone. It is better to let people decide for them selves.
 - Naming of toolbars is primarily the responsibility of the WB maintainer. They know their design philosophy best.
 
It is a known issue with FreeCAD but there is not a definite solution yet.
I have placed the issue on the roadmap for the long term. (See my wiki in this repo)

**Comment by raindropsfromsky** [comment]
Ah, I get it!
Thanks!
