### ISSUE TITLE
Unable to set icon size for Draft and Surface workbenches

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#132]
I am unable to set the icon size for the Draft and Surface WBs.

In both cases, the panel listing seem to have one mismatch, as show below:
![image](https://github.com/user-attachments/assets/fff2fe90-1785-4f57-95c2-5eb35c427699)

![image](https://github.com/user-attachments/assets/307fad63-07cf-4c23-98bb-b342cb3df337)

Probably this mismatch causes this issue.

Ribbon Wb 1.4.1 on FC 1.1.0Dev (win 11)

**Comment by APEbbers** [comment]
Hi,

I've fixed the issue. You only see one version of the view panel which is set in the preference window.
The panel in the ribbon is named "Views". The ribbon layout dialog will show "View", "Views - Ribbon" or "Individual views" depending on the setting.

kind regards,
