### ISSUE TITLE
FR: Change all icons size with a single click.

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#136]
Would be possible to change size to all small/medium/large with a single click on the header? Alternatively 3 buttons to change all sizes.

![image](https://github.com/user-attachments/assets/b8ca6e2b-36db-4b1d-9034-911607c52acc)

**Comment by APEbbers** [comment]
Hi

For the next version I have planned to improve the design menu. I'll pick this up and implement this along the way.
I've created a roadmap in my wiki, to show the plans that I currently have for this workbench: [https://github.com/APEbbers/FreeCAD-Ribbon/wiki/07-%E2%80%90-Road-map](url)

**Comment by hasecilu** [comment]
I tested this on the dev branch: on the UI all marks are moved as expected but after restarting FreeCAD no changes were appplied.

**Comment by APEbbers** [comment]
Hi,

It took me a while, but it should work again.

**Comment by hasecilu** [comment]
Hi, I tested again and changing the size for all icons in a WB (Reinforcement and CfdOF) with single toolbar resulted in the change being done but trying the change on Wb with multiple toolbars (Curves, Quetzal (dodo fork)) resulted on the changes not being done on all toolbars except one. I made many attempts but despite the clicks done only one toolbar per WB seems to be saved.

**Comment by APEbbers** [comment]
Hi, I tried to repoduce the error, but it works fine for me on both Windows and Linux. (I have the curves WB installed)
I will adapt the code so that a complete json file is generated, see if that changes anything

**Comment by hasecilu** [comment]
I made more tests and resulted that the toolbars which names are translated are the ones that do not save the changes, the toolbars that remains with the same name (translated or not) are the ones that have applied changes. (I have translation progress on Curves WIP!)
