### ISSUE TITLE
Ribbon Preferences window is too tall above 1080 pixels

### ISSUE THREAD

**Issue by julianjc84** [APEbbers/FreeCAD-Ribbon#138]
The Ribbon Preferences window is too tall above 1080 pixels displays
and not able to be resized.

**Comment by hasecilu** [comment]
At the moment of opening not all elements are properly displayed (Hyprland) but now the window can be resized!, Do you have latest version?

![image](https://github.com/user-attachments/assets/cab32155-de79-411f-bb7c-6e7c54fb6131)

**Comment by julianjc84** [comment]
1.4.2
the preference window can be made taller, but the shortest allowed is over 1651pix
![image](https://github.com/user-attachments/assets/6a31d189-f667-439e-ae2c-11951e1be686)

**Comment by hasecilu** [comment]
Normally FreeCAD preference pages automatically have a scrollbar when it's needed but since this is a standalone window the scroll have to be implemented on the UI file.

**Comment by APEbbers** [comment]
Hi,

I've added a scrollbar feature in both the layout dialog as in the preference dialog

kind regards
