### ISSUE TITLE
Update license string in package.xml file

### ISSUE THREAD

**Issue by chennes** [APEbbers/FreeCAD-Ribbon#15]
https://github.com/APEbbers/FreeCAD-Ribbon/blob/0c44fbfd065c9ba770c6d7598040dd15ecf71ad2/package.xml#L14

With apologies if you used the built-in Developer Mode to create this file -- it had a bug in the license string generation, this line should read
```
<license file="LICENSE">GPL-3.0-or-later</license>
```
(see https://spdx.org/licenses/)

Thanks!

**Comment by APEbbers** [comment]
Thanks for the headsup. I've changed the text in package.xml
