### ISSUE TITLE
The toolbar for the Techdraw WB does not show many of the panels listed in the Ribbon Design UI.

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#152]
The toolbar for the Techdraw WB does not show many of the panels listed in the Ribbon Design UI.

![image](https://github.com/user-attachments/assets/70fc0420-6d89-491a-ae01-9b804daf0018)

**Desired:**

All panels listed in the Ribbon Design dialog should be shown in the Ribbon.

**Comment by APEbbers** [comment]
I've had that a couple of times. It will be solved when you set the TechDraw Workbench autoloaded.

I'm currently testing a cache function. hopefully I can use it to solve this kind of issues

**Comment by raindropsfromsky** [comment]
Should I raise this bug at FC GitHub?

**Comment by APEbbers** [comment]
This can be a bug where FreeCAD is not properly loading the WB. So you may raise it at FC Github.
I'm looking into it however.

**Comment by APEbbers** [comment]
Hi,

I suspect that the test workbench is the cause of the workbenches not loading properly. I've currently the test workbench disabled and no problems so far. Perhaps you can give it a try as well?

**Comment by raindropsfromsky** [comment]
I do not have a WB called "Test" in the WB toolbar in the Ribbon WB UI.
I checked the Addon Manager also. It does not have any Test WB.

![image](https://github.com/user-attachments/assets/275b4320-67a9-41a5-a9da-a46816ad6cda)

(Note that I have selected "any workbench" filter.)

**Comment by APEbbers** [comment]
it is not an normal add-on. You have to look under preferences -> workbenches. There you will see a wb test:
![image](https://github.com/user-attachments/assets/9a694f7e-a2a1-46a6-a364-56b375f9ffb8)

**Comment by raindropsfromsky** [comment]
I found the **Test framework** WB in **Preferences**.
It was already unchecked for me from the start. 
Yet I had faced the issue.

**Comment by hasecilu** [comment]
Similar to last comment on #130 "Dimensions custom" panel is empty.
![image](https://github.com/user-attachments/assets/ae97b40b-2943-4782-abf8-033aa2acf6f5)
