### ISSUE TITLE
Ribbon is unable to work on the Sketcher wB

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#157]
Earlier, Ribbon WB was able to control the toolbar settings for the Sketcher WB. 
But now it cannot set the button size for Sketcher WB.

As in other WBs, the panel list does not match the actual ribbon.
![image](https://github.com/user-attachments/assets/ef804154-90e2-4fed-aee5-9587731a9a3e)

**Comment by APEbbers** [comment]
Hi, 

in the picture you have the Part Design WB selected instead of the Sketcher WB.

**Comment by raindropsfromsky** [comment]
No. The picture shows the Sketcher wB (the tab of the selected WB turns lighter gray).

For comparison, if I select the PD WB, the Ribbon UI looks like this:
![image](https://github.com/user-attachments/assets/8f7356b8-a0b1-4a22-baa4-fbe3b2a93a8b)

**Comment by raindropsfromsky** [comment]
oops!

Please ignore the screenshot.
However, the problem is that I am still unable to change the size of the create sketch button to "small".
After I change the size, close the **Ribbon Design** dialog, and restart FC, the size remains the same (large).
![image](https://github.com/user-attachments/assets/bee0ffdf-29a1-445e-ab83-8c7e8727413f)

If I launch the **Ribbon Design** dialog once again, it shows the size for this button as "large", as if I had never tried to change the size to "small".

**Comment by APEbbers** [comment]
Hi,

I see what you mean. it is specific for this button as far I can see. I'm on it!

**Comment by raindropsfromsky** [comment]
Just to update the status for 1.4.6:

I am unable to change button size for the following WBs: Sketcher, Draft, and Mesh.
I could change the button sizes in the other WBs.
So there is a likelihood of a pattern among these WBs (as compared to the rest).

Note that I have not activated all WBs.
I have only the following WBs (problematic WBs are marked with an X):
- Curved Shapes
- Curves
- Draft---> X
- Fasteners
- Mesh ---> X
- Part
- Part Design
- Sheet Metal
- Sketcher ---> X
- Spreadsheet
- Surface
- Tech Draw

So there may be more WBs with this problem, which I have not noticed!

**Comment by APEbbers** [comment]
Hi, I found the cause. It seems a bug in FC 1.0. FC 1.0 is not returning these commands. in FC 0.21 it is working as normal

I'll have a look if I can work around it. The ribbon itself has a different method. i check if I can adapt this.

**Comment by raindropsfromsky** [comment]
I hope that takes care of all the "faulty" WBs!
(And possibly more WBs that I have not installed...)

**Comment by APEbbers** [comment]
Hi,

Do you know which command specific are not working?
I have created a list which adds the missing commands. I can update that with other commands as well

_"MissingCommands = [
        ["Sketcher_NewSketch", "Sketcher_NewSketch", "Create sketch", "SketcherWorkbench"],
    ]"_

Thanks in advance!

I've fixed the bug in the develop branch.

**Comment by raindropsfromsky** [comment]
Sure, here is the list:

**Draft WB:** Line, Move, Manage layers..., Snap lock, 
**Mesh WB:** Replace object, Check geometry

**Comment by APEbbers** [comment]
Hi,

I found the issue! it was caused because the same commands were used in multiple workbenches.
In the background I'm creating lists of workbenches, toolbars and commands. I have filters to avoid duplicates. One of these filters filtered these commands, which resulted that the layout menu ignored these commands.

in version 1.4.8 it is fixed.

kind regards
