### ISSUE TITLE
Small icon size makes icons disappear

### ISSUE THREAD

**Issue by MarcelP102** [APEbbers/FreeCAD-Ribbon#163]
Freecad Light theme.

Setting the small icons to 20 makes them invisible:
![afbeelding](https://github.com/user-attachments/assets/781254a2-5d2c-43ec-b901-ba8705a64708)

Setting them to 25 makes the text hard to read:
![afbeelding](https://github.com/user-attachments/assets/9ce13ceb-648a-461b-aae9-f7e94fd6bd8c)

**Comment by APEbbers** [comment]
Hi,

Thanks for bringing it up! It is solved with version 1.4.7.

kind regards
