### ISSUE TITLE
Ribbon scrolling not working with different sizes for icons

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#169]
When trying to change the small icon sizes to something bigger and trying to scroll the ribbon it scrolls up and down and also left and right. When it's only meant to scroll left and right.

![image](https://github.com/user-attachments/assets/e900f3c1-0865-453e-b0dd-f569ffb63612)
![image](https://github.com/user-attachments/assets/1c0a6482-e4d9-4f6e-a5ec-9fde0cdb7009)

```
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Fusion
Installed mods: 
  * fasteners 0.5.31 (Disabled)
  * lattice2 1.0.0
  * Manipulator 1.5.7
  * parts_library
  * Alternate_OpenSCAD 1.0.0
  * CurvedShapes 1.0.13
  * FreeCAD-Ribbon 1.4.7
  * SearchBar 1.0.2
  * OpenTheme 2024.9.1
```

**Comment by APEbbers** [comment]
Hi,

the issue is fixed in version 1.4.9

kind regards
