### ISSUE TITLE
Ribbon UI does not follow the settings of the Workbench selector in Preferences.

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#172]
My Preferences are set as follows
![image](https://github.com/user-attachments/assets/108c1cbb-a9c9-41c5-bb47-57e2dd49d215)
According to this setting, FC should present all WBs in a dropdown list, and show only icons for the WBs (without the text labels). (see [user manual entry](https://wiki.freecad.org/Std_Workbench/en))

However, the Ribbon Wb always shows the WBs in **Tabbar** mode, and cannot hide the text labels.

![image](https://github.com/user-attachments/assets/e375c415-9619-402e-8e8c-a583e85f576b)

**Comment by APEbbers** [comment]
These are separate things. the setting you mentioned is for the toolbar "workbench" in the toolbar UI.
The ribbon setup differently and doesn't work like that. 

It has nothing to do with FreeCAD but with the python package PyQtRibbon.py
