### ISSUE TITLE
Let Ribbon WB use the default WB toolbar

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#186]
Before installing the Ribbon UI, I was able to set the preferences to show only icons in the WB Toolbar.
![image](https://github.com/user-attachments/assets/ca666499-a941-4aa0-9bb9-a3173272c1d4)

I prefer this toolbar because it does not show text labels, and therefore it is much compact.

But after installing the Ribbon WB, this toolbar is replaced with a custom toolbar.
![image](https://github.com/user-attachments/assets/4263330e-f316-40ff-9bb9-2ccb964fde9e)

Unfortunately, this toolbar has a lot of text, which makes it too long. 
We have to scroll on it to reach the WBs on the right.

**Desired:** Use the default WB toolbar (which can be controlled from the **Preferences**.)

**Comment by APEbbers** [comment]
See my answer in #121 and my roadmap https://github.com/APEbbers/FreeCAD-Ribbon/wiki/07-%E2%80%90-Road-map
