### ISSUE TITLE
Bug: (Develop) Typing on "Exclude panels" tab raises error

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#187]
This appears and then  list got emptied.

![2024-12-03-082448_hyprshot](https://github.com/user-attachments/assets/acc046fd-99d3-430e-b4c3-928313c0a655)

**Comment by APEbbers** [comment]
Hi this is now fixed

**Comment by hasecilu** [comment]
Jus trying to open the window this error appeared, it didn't open

![image](https://github.com/user-attachments/assets/a2aa0b3b-d4b3-473a-99ac-8c8f47f3e642)

**Comment by APEbbers** [comment]
Ah sorry, was about to add that you need to reload the workbenches again.

I had to store the translated menutext as well.

If reload doesn't work, delete the .dat file. Then the dialog will create a new one

**Comment by hasecilu** [comment]
Done, working. Had to test on old laptop because seems that system update broke FreeCAD. Edit: It seems it was a `pyside6` package update on Arch Linux, fixed now
