### ISSUE TITLE
Bug (Develop): When using "Reload workbenches" button error raises

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#188]
Despite the error I didn't noticed any problem with the ribbon.
Even with the debug mode set on the preferences there is no message on the console that gives a clue on the specific WB on which was the problem.

![2024-12-03-105318_hyprshot](https://github.com/user-attachments/assets/1824bb91-915f-489e-bb6c-747a5b58e891)

**Comment by APEbbers** [comment]
Hi,

I added:  if "pixmap" is None: pixmap = "".
This should solve it, I believe
