### ISSUE TITLE
Missing icons in sketcher

### ISSUE THREAD

**Issue by MarcelP102** [APEbbers/FreeCAD-Ribbon#196]
See edit tools: 

![afbeelding](https://github.com/user-attachments/assets/56c6d493-8231-4aad-9790-6bba180226bb)

**Comment by APEbbers** [comment]
Hi,

That's probably because the data file is not generated yet. Can you test if it helps when you open the layout menu? The first time it will ask you to load the workbenches. When pressed "yes" a data file is generated. This is used as backup for the icons in the ribbon and for loading the layout menu faster

**Comment by MarcelP102** [comment]
Yeah I already did that. But when I reload the workbenches in the ribbon design dialog I get this error:
![afbeelding](https://github.com/user-attachments/assets/4c4cb91b-4f39-45a3-90b2-ca72a1f0a69e)

![afbeelding](https://github.com/user-attachments/assets/1f89b5d6-5678-419a-86ad-5e13eedea97d)
The icons in sketcher are still missing.


Also another issue; the ribbon design dialog is behind the freecad main screen after reloading the workbeches.

**Comment by MarcelP102** [comment]
When you create a new sketch the icons do show up, hmm..

![afbeelding](https://github.com/user-attachments/assets/e6b78ae5-64cd-48f5-af98-35c99873dabd)

**Comment by APEbbers** [comment]
I'll have a look tonight. it is the normal behavior for these buttons. To cover this, the Icons, should be taken from the data file. But somehow this functionality is broken. At the moment it does work on my side, but I'll do some tests

**Comment by MarcelP102** [comment]
Somehow the icons in sketcher now works correctly. But reloading the workbenches in the ribbon design dialog still give the same error

**Comment by APEbbers** [comment]
Hi,

The issues should now be fixed. Regarding the missing Icons in the sketch wb, I couldn't reproduce the issue, but I keep it in mind.

kind regards
