### ISSUE TITLE
Import layout seems not to work

### ISSUE THREAD

**Issue by MarcelP102** [APEbbers/FreeCAD-Ribbon#197]
When I import the layout JSON I exported before nothing seems to happen? The 'update' button is still grey, I can only chose 'cancel' or 'close'. Both buttons don't seems to activate the imported layout.

**Comment by APEbbers** [comment]
Hi, the issue should now be fixed. Along with the issue that native dropdowns were not showing correctly on new panels.

**Comment by MarcelP102** [comment]
It's working now, thanks!
