### ISSUE TITLE
Global toolbar Views and Tools shown twice, unable to delete

### ISSUE THREAD

**Issue by MarcelP102** [APEbbers/FreeCAD-Ribbon#202]
Hi,

As you can see a fresh install of the ribbon gives twice the entry of Views and Tools
![afbeelding](https://github.com/user-attachments/assets/2af57882-619d-408c-a75c-f178d8e8da8d)

I think these are the custom Tools and views panel?
![afbeelding](https://github.com/user-attachments/assets/06350897-f1fc-42a7-a54b-e70d4a9fa9ce)

I'm not able to delete them. After restart those pannels still show up.

Also when pressing the remove button to many times I get this error:
![afbeelding](https://github.com/user-attachments/assets/cfedc800-df83-4a62-a9a6-fdc3fb15db36)

**Comment by APEbbers** [comment]
Hi,

It is fixed. It follows the settings under preferences again. 
![image](https://github.com/user-attachments/assets/eb5febf9-32e7-4898-90e1-8cc4f069b8e0)

kind regards
