### ISSUE TITLE
Three bugs when I launch Ribbon WB's "Customize > Ribbon Layout" menu command

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#207]
I tried out the Ribbon WB's **Customize > Ribbon Layout** menu.

But I see this error: **[BUG#1]**
![image](https://github.com/user-attachments/assets/6b6bd423-ef44-4270-8324-a8669f750f03)

After that, I see this screen: **[BUG#2]**
![image](https://github.com/user-attachments/assets/c01cd8a1-8df4-409b-9c42-01e904f31401)

After that, I see this screen: **[BUG#3]**
![image](https://github.com/user-attachments/assets/96968890-d454-4fe6-8c90-3d3e63809485)
I expected the "Reload the WBs" message to disappear after I select it once.

OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.39708 (Git) Conda
Build type: Release
Branch: main
Hash: 173ff4da1ef4f075d56c0dc617d1bf00d5f49d4b
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Beltrami 1.1.0
  * CommandPanel
  * CurvedShapes 1.0.13
  * Curves 0.6.52
  * dodo 1.0.1
  * ExplodedAssembly
  * fasteners 0.5.33
  * frame 0.1.1
  * FrameForge 0.1.0
  * FreeCAD-Ribbon 1.5.0
  * freecad.gears 1.3.0
  * FreeGrid 2.1.1
  * OpenTheme 2024.9.1
  * SearchBar 1.2.1
  * sheetmetal 0.6.12
  * Silk 0.1.5
  * symbols_library

**Comment by APEbbers** [comment]
Bug #1: 
This is probally from the fasteners workbench and not the Ribbon. 
![image](https://github.com/user-attachments/assets/73156729-3119-4b42-a6e6-6beb55f5bed0)

Bug#2:
Can you try when you remove the RibbonStructure.json? and see what happens? And also the .dat files?
Do you have sufficient rights in the folder were the addons are located? I tried to repoduce, but I have no problems at all.
(I'm also on windows with FreeCAD 1.0dev)

Bug#3:
This is not a bug, but just a warning that reloading can take a while. It is there permanently.

**Comment by raindropsfromsky** [comment]
**Bug#2:**
I have not changed the paths this time, and I have never had any issue like this so far.
So it may not be related to the access rights.

Mine is FC 1.1..0 dev (not 1.0 Dev). Could that be the reason?

------------------------

The RibbonStructure.json is located at-
C:\Users\<UserName>\AppData\Roaming\FreeCAD\Mod\FreeCAD-Ribbon
I have "full control" (read, write, modify, execute) on the file and the folder.

I closed FC, and then moved the RibbonStructure.json file and two dat files to a local folder.
FC started normally.
I could launch the "**Customize > Ribbon Layout**" command without any issue.

---------------

**Bug#3:**

IMHO this must not be permanently placed there.
After the user presses the **Refresh** button, the control should be removed.

(If the UI keeps showing him the same message, he concludes that his previous attempt failed.)

In FC itself, the Addon Manager provides an excellent example for handling the refresh:
It shows a progress bar (1), a button to stop the refresh (2) and the current status (3):
![image](https://github.com/user-attachments/assets/a330d781-523c-405b-bf65-246038b3cb27)


![image](https://github.com/user-attachments/assets/8e93e37d-e740-418f-9627-3d550a8ba5b0)
![image](https://github.com/user-attachments/assets/5e47d895-1030-46d6-8ffa-5d11d80b9d85)

It would be great if a similar UI is provided in Ribbon also.

**Comment by APEbbers** [comment]
Bug#2: when you see this, what is reported in the report view? perhaps it is a specific workbench that causing this issue.

**Comment by raindropsfromsky** [comment]
You mean bug#1? (Nonetype object)
I am not getting it any longer!

I am not getting bug#2 either

**Comment by APEbbers** [comment]
OK. I'm parking this for the moment then. 

Regarding bug#3: I've tried this, but because the dialog was freezing until the very end. so I abandoned it. I'll keep it in mind though
