### ISSUE TITLE
Add same panel proprieties like task panel: transparency, overly,....etc....

### ISSUE THREAD

**Issue by dgrabulosa** [APEbbers/FreeCAD-Ribbon#214]
I manage to obtain a clean panel distribution, but I have some errors.
- task panel appear that have same height as the ribbon.
- the ribbon panel generates an error If I try to click in the FreeCAD main icon.

Maybe if the ribbon panel have the same tools that have the task or tree pane in the header: transparency, overlay,...... can help.

OS: Windows 11 build, 22631
Architecture: x86_64
Version: 1.1.0dev.39708 (Git) Conda
Build type: Release
Branch: main
Hash: 173ff4da1ef4f075d56c0dc617d1bf00d5f49d4b
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Spanish/Spain (es_ES)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * FreeCAD-Ribbon 1.5.0.4

![Captura de pantalla 2024-12-25 002527](https://github.com/user-attachments/assets/ec655815-a7dc-4524-a9ab-86698322d7f8)

**Comment by APEbbers** [comment]
Hi,

I created the custom overlay function, because the original overlay function is interfering with the ribbon.  The Ribbon is excluded from the overlay function. How did you get the ribbon transparant? That shouldn't be possible with the custom overlay function. Perhaps that's causing the error.

Regarding the task panel and tree, You can drag these to somewhere else. Click and hold the header, then you can drag the task panel.

**Comment by APEbbers** [comment]
Hi,

I found a possible solution. Can you try my develop branch? You might have to set this option:
![image](https://github.com/user-attachments/assets/301b89ec-bc92-46ff-9ca8-15a6ccf461b5)

@hasecilu and @raindropsfromsky: Can you perhaps test as well this if this works? it might be a better solution for the problems with overlay and keep the native functionality instead

Kind regards,

**Comment by hasecilu** [comment]
What exactly need to be tested? For what I see if you set the autohide option you are forced to click on the WB tab to show again the ribbon, should be on hover?

**Comment by raindropsfromsky** [comment]
> if you set the autohide option you are forced to click on the WB tab to show again the ribbon, should be on hover?

I agree. The ribbon should appear on hover. Otherwise it will eat up too many clicks!
In addition, if we hover the mouse on another WB (tab), FC should open that tab.

Also, what are the other features to be tested? Please do share!

For example, this particular thread started with the idea to have a transparent ribbon.
That is interesting! (Just like transparent tree panel)
Are you planning to implement that?

**Comment by APEbbers** [comment]
Hi,

I'd like to test if FreeCADs Overlay function causes any issue with the ribbon. When you click on the ribbon and then press F3, the ribbon should become transparant but not hidden when you have a part open. 

I've also fixed a bug in the PyQtRibbon package which was caused by hovering over the application button in overlay mode

(edit:) The forced click still remains. but this is actually the same behavior as wtih MS Office, so let that be for the moment.

**Comment by APEbbers** [comment]
> > if you set the autohide option you are forced to click on the WB tab to show again the ribbon, should be on hover?
> 
> I agree. The ribbon should appear on hover. Otherwise it will eat up too many clicks! In addition, if we hover the mouse on another WB (tab), FC should open that tab.
> 
> Also, what are the other features to be tested? Please do share!
> 
> For example, this particular thread started with the idea to have a transparent ribbon. That is interesting! (Just like transparent tree panel) Are you planning to implement that?

Hi, Yes if there are no issues, I'd like to implement this. I still provide the custom function as a backup. Which can be set under preferences.

If you like, in the develop branch I have implemented text wrapping for large buttons. It just wraps to two lines. everything beyond that, is not visible. What is your view on this?
![image](https://github.com/user-attachments/assets/b89ef955-631e-4302-a50b-0ab54bb6bf9c)
![image](https://github.com/user-attachments/assets/cdabef3a-0866-4228-900b-057889beacf4)

**Comment by raindropsfromsky** [comment]
Well, the selection status of the menu options is not clear:
![image](https://github.com/user-attachments/assets/d8a0ee14-c4f6-4f44-914b-53581d42e6b0)

Usually, we should see a tick, or a dot against the menu that is selected.

I like the idea of text wrap with large/medium buttons.
The small buttons do not have that much width, so they cannot have text wrap.

**Comment by APEbbers** [comment]
Ok. I'll add dots at the end. But what happens when you click on the ribbon and press F3? (Or go to view->Docview overlay.
If it is not there you have to activate it first:
![image](https://github.com/user-attachments/assets/5c7713a0-7488-4564-b91a-6396097aea91)

Maybe also a good idea to have some panels activated. You can then right click on them to enable the ribbon or other panels.
It is best in my experience to have the start page activated. Then you can always open a part, which shlould make the ribbon beome visible. (Shoud solve the issues from the past regarding the overlay)

**Comment by raindropsfromsky** [comment]
Actually the logic is not clear to me. 

1. What is "overlay" mode?
2. Can we have four different combinations of overlay and transparency modes?
    (on+on, off+on, on+off, off+off)
3. How is F3 supposed to interact with these two modes?

**Comment by APEbbers** [comment]
In the latest commit I added a restore function.
If you put in a file named "OVERLAY_DISABLED" (no extension), the custom overlay function will be triggerd which restores the ribbon
![image](https://github.com/user-attachments/assets/c37b0530-0de0-472a-8294-d3153d8cfe74)



> Actually the logic is not clear to me.
> 
> 1. What is "overlay" mode?
> 2. Can we have four different combinations of overlay and transparency modes?
>    (on+on, off+on, on+off, off+off)
> 3. How is F3 supposed to interact with these two modes?

You find the overlay function from FreeCAD here:
F3 triggers the first command.  The modes you previously mentioned are now hidden when the original overlay function is used.
The belong to my version.
![image](https://github.com/user-attachments/assets/3029b84b-5529-485c-a183-1d1b177bc19f)

**Comment by hasecilu** [comment]
Mmm, OK I needed that last setting, after that pressing `F3` made switch to Overlay mode.

The ribbon no longer takes al horizontal space. If you try to move it to the top it comes back to normal mode.

- Arrow to move scroll right is hide by task panel.
- Tooltip background changed to dark color

![image](https://github.com/user-attachments/assets/56f845eb-458d-48d1-b07a-f408c2a81c48)

**Comment by raindropsfromsky** [comment]
I tried to press F3 and got some weird results.
The layout changes completely.

Before selecting the **Activate overlay handling** option, pressing F3 toggled the UI like this:
![image](https://github.com/user-attachments/assets/d18dbae5-85c3-4bb9-be83-f75c6a65b440)
![image](https://github.com/user-attachments/assets/248452b6-7974-4d94-a9b2-a08770556a7b)
This is totally confusing!

After selecting the **Activate overlay handling** option, pressing F3 made the ribbon shrink a little, and after that, it disappeared completely, leaving the screen completely blank. 
![image](https://github.com/user-attachments/assets/394ffd9f-ba5d-4b71-b2c9-b3e90ccadf9b)

This is terrible!
First of all, I have not really understood how this overlay feature is supposed to work, or add value.

**Comment by APEbbers** [comment]
Can you open a part by double clicking in texplorer? the ribbon should appear then.
Also for this I have the start page enabled,. i then can open an recent file or example

**Comment by raindropsfromsky** [comment]
I restarted FC and the UI got restored.
But still I am not clear about what the overlay mode is supposed to achieve.

**Comment by APEbbers** [comment]
The idea of the overlay function is to lay over the viewport with the 3D model instead next to it. Combined with transparency, It looks like this:
![image](https://github.com/user-attachments/assets/32480889-d98b-40f7-8337-41c21a9d7dda)

**Comment by raindropsfromsky** [comment]
@hasecilu I am unable to click on your image to see its magnified view.

**Comment by APEbbers** [comment]
I can add this as an option with the comment "Use at your own risk"? and set the custom overlay function as default

**Comment by hasecilu** [comment]
With overlay mode you are able to interact with the 3D view even when clicking above other panels and also the transparency to see the the 3D view, it's really useful with small display because sometines panels takes too much spaces.

Try reloading the page because I updated the image.

**Comment by raindropsfromsky** [comment]
> It supposed to look like this:

No, I do not achieve that state at all. (Transparent toolbars over the canvas).
Instead, pressing F3 changes the panel layout totally!

**Comment by hasecilu** [comment]
It also changed layout for me but manually restored, probably a FreeCAD thing

---

I like the tree view and properties to take space to the top but don't like the cube up there, maybe always below the ribbon, left to the task panel is a better choice, but that's probably something that should be done on main FreeCAD.

**Comment by raindropsfromsky** [comment]
Only the mode is supposed to change with F3, and not the layout, right?

Secondly, why give F3 when the same mode is available from the menu system??

Thirdly, the menu system does not show "F3" shortcut:
![image](https://github.com/user-attachments/assets/1079152d-af81-4696-b7a3-101c1a2de8c5)

**Comment by APEbbers** [comment]
Thoes are the buttons from the custom overlay function. in the latest commit, they are hidden when The overlay function of FreeCAD is used.

**Comment by raindropsfromsky** [comment]
I am using Ribbon 1.5.0.5, but it is totally buggy.
1. The menu system does nnot show the status of the overlay and transparency.
2. The layout changes whenever I press F3. Restoring it is a big task (I don't know how)

**Comment by APEbbers** [comment]
Can you switch to the develop branch? the changes are there not in version 1.5.05.

**Comment by raindropsfromsky** [comment]
> Thoes are the buttons from the custom overlay function. in the latest commit, they are hidden when The overlay function of FreeCAD is used.

I  am afraid I did not get that!

I have selected the **Activate overlay handling** option in the **Preferences**.

But I do not know how the menu system is supposed to work.
What are the steps to check this out?

**Comment by raindropsfromsky** [comment]
The names of the branches have changed:
![image](https://github.com/user-attachments/assets/c7bc918d-b27f-4318-ae14-e0fff802051e)
Which branch should I select?

**Comment by raindropsfromsky** [comment]
I selected the "**origin/develop**" branch.
It produced this error:
![image](https://github.com/user-attachments/assets/02fed39e-35ab-4ed7-9aeb-1da7fdb95ab6)

**Comment by APEbbers** [comment]
Not an error, but a warning. click "yes". maybe you have changed something in a file?
Anyway it is best to update to the latest version

**Comment by raindropsfromsky** [comment]
I updated the version to 1.6.x.

The warning refers to repo, not the local file.
The latest version also has the same buggy behavior. 
(The toolbar has no transparency, the side panels change to undesired combo.)

**Comment by APEbbers** [comment]
Did you enable the overlay function?
![image](https://github.com/user-attachments/assets/10e49a67-e1cc-450a-9656-52131e0bd4cd)

**Comment by hasecilu** [comment]
Try `Shift+F3` for transparency.

**Comment by APEbbers** [comment]
@hasecilu do you think I should implement this as an option?

**Comment by raindropsfromsky** [comment]
I toggled the overlay using the **Overlay > Toggle overlay** menu.

It has some change in the canvas area:
![image](https://github.com/user-attachments/assets/09bba1df-c34f-4c9d-aa58-0b74c863742b)
![image](https://github.com/user-attachments/assets/1f94f391-9717-40d6-a46e-029b3f94433e)

Pressing F3 has the same effect.
Therefore I conclude that the menu should display F3 hotkey against this menu option.

Toggling the transparency using the **Overlay > Toggle transparency** menu does not change anything.

**Comment by raindropsfromsky** [comment]
Pressing SHFT+F3 behaves exactly like pressing F3.

BTW after I click in the ribbon area, and then press F3 (or SHFT+F3), then the focus is lost from the ribbon area.
If I press F3 (or SHFT+F3) again, it has no effect.
I have to click in the ribbon area and then press F3 (or SHFT+F3).

I expected that the focus will remain in the ribbon area, so F3 and SHFT+F3 keeps toggling the overlay state without needing clicking in the ribbon area repeatedly.

**Comment by APEbbers** [comment]
In this picture below you see what the keys should do: (This is FreeCAD itself)
![image](https://github.com/user-attachments/assets/a6f32793-0bf8-4a63-a92a-175ac785f618)
 If you press F4/shit F4 instead. All panels will be triggered.

I just found out that you need to set the theme correctly:
![image](https://github.com/user-attachments/assets/f344ad56-ac18-4c51-8c67-04d24effaf1b)

**Comment by raindropsfromsky** [comment]
I prefer opendark theme.
![image](https://github.com/user-attachments/assets/f9882c40-5c05-4bf5-8b1d-7d56ded35c53)

**Comment by APEbbers** [comment]
Just tested it with those settings and it should work.
![image](https://github.com/user-attachments/assets/45df3268-dd71-4224-a003-ab0818e0889b)

**Comment by hasecilu** [comment]
> @hasecilu do you think I should implement this as an option?

**I think it's more useful to make the ribbon to show automatically when hovering than trying to make it work on the overlay** mode because 
- the free space left by the ribbon that lets you see the 3D view doesn't let you to interact with it, if you instead hide the ribbon you can interact with all the free space
- OP mentioned to add the tools that other overlay-ed panels have but already is there!
![image](https://github.com/user-attachments/assets/e0de9ec9-60e0-4fc7-993d-8b900134ead5)

- last changes make the ribbon to not behave as previously: hivering over quick access buttons  activate the "move" cursor is shown which ibnterferes with normal functionning, quick acees buttons don't activate (you need to press 2 times fast), scroll no longer working, WB tab and ribbon

**Comment by raindropsfromsky** [comment]
> Just tested it with those settings and it should work!

I don;t think your settings are the same. The canvas should look dark with my settings.

**Comment by raindropsfromsky** [comment]
I tried again, and this time it worked, but partly.
![image](https://github.com/user-attachments/assets/e803270b-43e7-4b0a-8812-325fea92d4a6)
As shown, the Ribbon UI has become transparent, but it has moved to one side.

**Comment by hasecilu** [comment]
> I tried again, and this time it worked, but partly. ![image](https://private-user-images.githubusercontent.com/9047168/398591207-e803270b-43e7-4b0a-8812-325fea92d4a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDc4NDEsIm5iZiI6MTczNTE0NzU0MSwicGF0aCI6Ii85MDQ3MTY4LzM5ODU5MTIwNy1lODAzMjcwYi00M2U3LTRiMGEtODgxMi0zMjVmZWE5MmQ0YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMTcyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjYwN2JlMmI0N2JlYjU4YzA2ZTFkMDlmNmRhYzA3NjhiNDE1MmQzNjA5OWUxNjBjOGEyOTY3Y2YxMDcxZGFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oOUERTEvkNMWj7PC_ZQfY1jiP2qr3p0wI6NGHqHv0B4) As shown, the Ribbon UI has become transparent, but it has moved to one side.

Did you get problems trying to click/scroll on the ribbon?=

**Comment by raindropsfromsky** [comment]
> Did you get problems trying to click/scroll on the ribbon?

No, but the ribbon and other panels gave me total grief by moving to unpredictable places. Cannot even move them back, as docking them is not so easy!

**Comment by APEbbers** [comment]
> > @hasecilu do you think I should implement this as an option?
> 
> **I think it's more useful to make the ribbon to show automatically when hovering than trying to make it work on the overlay** mode because
> 
> * the free space left by the ribbon that lets you see the 3D view doesn't let you to interact with it, if you instead hide the ribbon you can interact with all the free space
> * OP mentioned to add the tools that other overlay-ed panels have but already is there!
>   ![image](https://private-user-images.githubusercontent.com/53124818/398590648-e0de9ec9-60e0-4fc7-993d-8b900134ead5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDc4ODUsIm5iZiI6MTczNTE0NzU4NSwicGF0aCI6Ii81MzEyNDgxOC8zOTg1OTA2NDgtZTBkZTllYzktNjBlMC00ZmM3LTk5M2QtOGI5MDAxMzRlYWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE3MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZTE2MjIxZmQxMGIzOWNmYTU1YWJjNmI4MWViMThmNjI5Yjk0MTc0OTg1ZjNjMjI1NDdkYTI0NGI3ZTc5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YB9ftTStzSsS1MxgT26zety--MZTIAAqCbAZYScTw9E)
> * last changes make the ribbon to not behave as previously: hivering over quick access buttons  activate the "move" cursor is shown which ibnterferes with normal functionning, quick acees buttons don't activate (you need to press 2 times fast), scroll no longer working, WB tab and ribbon

Hmm, strange. I don't have these issues on both Windows and Linux Mint. I think I added just as an option for the time being
The automatically hovering is actually interfering with the overlay function because they have both an enterEvent.  If I enable that, the ribbon can disappear completely.

**Comment by APEbbers** [comment]
> > Did you get problems trying to click/scroll on the ribbon?
> 
> No, but the ribbon and other panels gave me total grief by moving to unpredictable places. Cannot even move them back, as docking them is not so easy!

It is probably that your tree is very wide. You can stretch it near the top where the black bar becomes visible
![image](https://github.com/user-attachments/assets/62200798-305b-4188-9aa1-7b3ec99fac4c)

There you can also click and drag

**Comment by raindropsfromsky** [comment]
My ribbon has jumped to the left side, and I am unable to dock it to the top of the screen (across its whole width).
Even after unlocking the toolbars, I do not see its header bar anywhere, so I am unable to dock it!

![image](https://github.com/user-attachments/assets/3f8cccdb-9d7d-4b7e-8ccf-e18567d79fdc)

**Comment by raindropsfromsky** [comment]
> It is probably that your tree is very wide. You can stretch it near the top where the black bar becomes visible

No, I changed its width, and even moved the other panels. But I am unable to drag and dock the ribbon because I cannot see its header bar.

**Comment by raindropsfromsky** [comment]
**Update:** 
I moved the other panels up. 
This resulted in bunching of all the panels at the top. 
FC showed a separate tab for sach panel. 

![image](https://github.com/user-attachments/assets/589a7594-3b46-4576-8ce3-56175651d8b2)

After that, I dragged the tab of the Ribbon and docked it across the top of the screen. (Phew!)

**Comment by APEbbers** [comment]
Okay, I'm adding this as an option. Not as a default. 
And I place a warning with a help text next to the setting.
![image](https://github.com/user-attachments/assets/f31e5090-7426-4533-bf59-f14d462812e4)

**Comment by APEbbers** [comment]
@hasecilu  and @raindropsfromsky  Thanks for testing!

**Comment by APEbbers** [comment]
@dgrabulosa I've added the origina Overlay function of FreeCAD as an option in the preference menu.
As you can see in the conversations, it can cause issues. That is why it is switched of by default.

If you have problems, place a file without extension named "OVERLAY_DISABLED" in the folder of the add-on. The Ribbon will be restored with the overlay function from this add-on.

kind regards

**Comment by dgrabulosa** [comment]
Ok, thanks for all effort put on these, I will test.
