### ISSUE TITLE
Feature request: Easier switch between workbenches

### ISSUE THREAD

**Issue by raindropsfromsky** [APEbbers/FreeCAD-Ribbon#219]
![image](https://github.com/user-attachments/assets/aab4445c-9e7f-47dc-a909-9366cc1bb81a)

The present design of Ribbon UI cannot have "icon only" option for the workbench toolbar.
This is a known limitation.

While we wait for a solution for that issue, can we have a better WB-selection mechanism?

For example, 
1. Let the < and > buttons scroll the entire screen-widthful of the WB buttons, rather than scrolling by one button at a time.
2. Let there be a user-selectable option for a drop-down list of WBs (instead of the WB toolbar)

**Comment by APEbbers** [comment]
Hi,

You can already scroll with the scroll wheel the whole bar instead one by one. For an temporary solution: You can place toolbars inside the status bar at the bottom. So you can place the WB there as a combobox:
![image](https://github.com/user-attachments/assets/c28564ae-0e01-4b60-aae9-19462833978c)

Kind regards
