### ISSUE TITLE
Please also show a dark theme example of the Ribbon in README

### ISSUE THREAD

**Issue by luzpaz** [APEbbers/FreeCAD-Ribbon#44]
Would it be possible to also add another screenshot of Ribbon in Dark theme ?

**Comment by APEbbers** [comment]
Hi,

Of course, I've added a second screenshot to the readme.

kind regards,

**Comment by luzpaz** [comment]
Thank you!

Just one more thing, what I'm missing in those screenshots is a clear close-up picture of ribbon UI. Is it possible to also add a screenshot of a zoom-in ?

**Comment by APEbbers** [comment]
Hi,

I've also added screenshot from the ribbon only
