### ISSUE TITLE
Is Ribbon UI ready for FreeCAD 1.0 Release?

### ISSUE THREAD

**Issue by luzpaz** [APEbbers/FreeCAD-Ribbon#53]
* https://github.com/FreeCAD/Addons/issues/13

**Comment by APEbbers** [comment]
I've one open issue: When "autohide  ribbon" is enabled or click twice on the collapse button of the ribbon, the ribbon disapears.

This issue is only with FreeCAD 1.0. (QT5 and QT6) There are no problems with FreeCAD 0.21.

**Comment by luzpaz** [comment]
> When "autohide ribbon" is enabled or click twice on the collapse button of the ribbon, the ribbon disapears. 

Can you open an issue for it so we can track it?

**Comment by APEbbers** [comment]
Done!

**Comment by luzpaz** [comment]
Looks like there is good activity here. Closing as this is an indication that any 1.0 bugs will be addressed. THanks!
