### ISSUE TITLE
Names of toolbars are not being translated

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#66]
A lot of built-in and external WB have been translated, including toolbar names. The names' translations are not shown in the ribbon. All this strings should be using the "Workbench" context but some external WB can have something different.

![image](https://github.com/user-attachments/assets/8e8b20c6-6ac7-4828-bc9c-9439f34213e4)

**Comment by APEbbers** [comment]
Hi,

See my response in: [ https://github.com/APEbbers/FreeCAD-Ribbon/pull/62#issuecomment-2444949454](url)

kind regards

**Comment by hasecilu** [comment]
Very nice, now translations are working OK, thanks! It's cool because normally the toolbar names only appeared when you hovered a bar pixel, which was hard because of the commands, now you have straight away the names.

![image](https://github.com/user-attachments/assets/85103800-27e3-44a3-bada-c5e9bca5c00b)
