### ISSUE TITLE
Trying to install FreeCAD-Ribon with error message

### ISSUE THREAD

**Issue by ucool321** [APEbbers/FreeCAD-Ribbon#69]
Hello

I've installed FreeCAD-Ribon with the Addon Manager. But at Start i will get the error message "QWidget::setMinimumSize: (Ribbon/QDockWidget) Negative sizes (0,-1) are not possible". 

There are no toolbars selected.  If i active the Panel "Ribbon". I can't select/add any toolbar anymore.

**Comment by APEbbers** [comment]
Hi,

Which OS are you using? And can you perhaps share a screenshot of the error message? 
You can try my develop branch in the meantime. I'm not loading the ribbon as a QDockwidget in that version.

**Comment by ucool321** [comment]
Here is a screenshot.

![freecad_ribbon_error](https://github.com/user-attachments/assets/0f19c753-61a3-42a2-8b28-edb1546d31df)

I using it on Linux.

**Version:** Freecad 1.0rc2
**System spec:**
CPU: quad core Intel Core i7-6700K (-MT MCP-) speed/min/max: 982/800/4200 MHz
Kernel: 6.6.58-1-MANJARO x86_64 
Mem: 32 GiB (25.3%)

**Comment by APEbbers** [comment]
I suspect it is related to this issue: #54. The solution for that issue can also work for this issue

**Comment by APEbbers** [comment]
Hi,

I've changed a setting in the script. can you give it a try with version 1.3.7.1?

**Comment by ucool321** [comment]
I've installed the new version.

For my understanding, the toolbar icons will be automaticly added in the "Ribbon" Panel? I made a screenshot and the ribbon panel stays empty. The "QWidget" error message is gone. See the second screenshot.

![new_screenshot_ribbon](https://github.com/user-attachments/assets/aba92912-9913-4f9b-b6f8-2796166c0542)

![new_screenshot_ribbon_2](https://github.com/user-attachments/assets/f68ed6f8-63c9-493c-9f83-d4ea55068443)

**Comment by APEbbers** [comment]
I'm not sure what is happening. do you have toggled overly by any change? You can check this by pressing "F3".
If so, the ribbon will be somewhere in the topleft corner. 
There is an issue with overlays which I'm working on.

**Comment by ucool321** [comment]
Yes I thing this has something to do with issue [54](https://github.com/APEbbers/FreeCAD-Ribbon/issues/54) what you posted earlier. May be its a upstream bug in Freecad.
