### ISSUE TITLE
FR: move ribbon while pressing button

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#81]
The panels on the ribbon are moved when button is released, could be changed to move when pressing the button, 2/3 times per second maybe? Mouse scroll works fine.
![image](https://github.com/user-attachments/assets/b757129c-2f2b-4cd6-9afe-2889a00376bd)

**Comment by APEbbers** [comment]
Hi, I've added a setting with which you can set the click "speed" in the develop branch. I have overridden the standard click event with a new one.

Can you try if it helps? The event is triggered when the button is pressed. Not when it is released. So it should be triggered only once.

**Comment by hasecilu** [comment]
Hi, it totally helps, I used the value of 10, not sure if other users may want a higher value.
