### ISSUE TITLE
Bug: Modifying `RibbonStructure.json` makes the FreeCAD Addon Manager to backup Ribbon WB directory

### ISSUE THREAD

**Issue by hasecilu** [APEbbers/FreeCAD-Ribbon#82]
Addon Manager can not do a clean pull because of the changes and clones the repo in another directory, this change makes the changes from users "lost", they need to manually copy that file again.

I think all user changes should be in a separated file, even separated in a WB-basis to prevent this issue.

Maybe even considering to put config files on `$XDG_CONFIG_HOME/FreeCAD/` would be a good option.

![image](https://github.com/user-attachments/assets/e96ee963-57e1-487c-b4f4-1578198a63c7)

**Comment by APEbbers** [comment]
If added the .json files to gitignore. When "RibbonStructure.json" is not present, a copy and rename action will be done with "RibbonStructure.txt".

I believe this should solve the issue

**Comment by hasecilu** [comment]
Yeah, I also think that should work. I can test when there is another change on main.

**Comment by hasecilu** [comment]
OK, it seems since the file is already commited, git tracks its changes, it should be removed from repo or use another name for the file generated by the user.

**Comment by APEbbers** [comment]
I've removed the files from the repo, so all .json files shouldn't be tracked anymore
