### ISSUE TITLE
Ribbon addon won't install properly on weekly build of FreeCAD-Bundle

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#94]
Tried installing the FreeCAD-Ribbon addon on the weekly build AppImage and I saw no visible changes to the UI. Tried creating a file and on the Report view I got this error:

```
11:17:44  During initialization the error "No module named 'pyqtribbon'" occurred in /home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon/./InitGui.py
11:17:44  Please look into the log file for further information
```

![image](https://github.com/user-attachments/assets/fb2f8e24-89b3-40d7-9d94-a24f0a567296)

Addons: OpenTheme ( + OpenTheme preferences pack )
OS: Linux Mint 22 ( Cinnamon )

**Comment by APEbbers** [comment]
Hi, 

I've fixed it with version 1.3.16.1. Thank you for bringing it up.
