### ISSUE TITLE
Collapse Ribbon and autohide functionality behaving unexpectedly

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#96]
When trying to use the collapse ribbon button for the second time or quickly move your mouse, the entire toolbar disappears unless FreeCAD is reset.
The toolbar also disappears if you enable autohide and quickly move your mouse up and down near it.

![image](https://github.com/user-attachments/assets/8962f8e7-775a-47f4-adc1-ef5d2ee17a93)
![image](https://github.com/user-attachments/assets/f7a068a8-b947-49ea-8c17-34fa5f476ad5)

FreeCAD-Bundle AppImage: weekly-build
Addons: OpenTheme ( + OpenTheme preferences pack )
OS: Linux Mint 22 ( Cinnamon )

**Comment by APEbbers** [comment]
Hi,

Thanks for bringing this up. I'm aware this issue. it is related to the new overlay function in FC 1.0. I have a fix in my development version, you can try that version if you like. There is not an issue with FreeCAD 0.21. I've raised an issue by FreeCAD as well as in this repo (#54 and [https://github.com/FreeCAD/FreeCAD/issues/17500](url))

you can try to press F3 to toggle overlays. sometimes that helps as well.
